### PR TITLE
Gridview

### PR DESCRIPTION
**Pull request by nomwerp**
anyone care to review ?  please also see screenshot

### CODE REVIEW

**Comment by amouly** [comment]
@nomwerp wow!! Nice feature. The only thing I see, is the overlapping of text in some of the rows. Maybe increasing the height of elements will help?

**Comment by nomwerp** [comment]
thanks,  yeah the overlaps get worse with real  (longer) data. it seems something is messed up with gridview,  all bits are set to wrap content for height but for some reason *some* of the rows that have text wrapping seem to get the wrong height...

**Comment by Pho3niX90** [comment]
An issue that I noticed throughout the project is that layout files referring to "dimen" resources that do not exist. Am I the only one that has this issue?

**Comment by nomwerp** [comment]
@Pho3niX90 i'd guess android sdk version issues?   for example: `@dimen/abc_text_size_large_material` seems to be defined in 
`build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.1.1/res/values/values.xml`

maybe build.gradle needs updating?
```dependencies {
    compile 'com.android.support:appcompat-v7:22.1.1'```

**Comment by Pho3niX90** [comment]
I made some changes to the files to prevent the overlap of text. I hope I did it correctly in github for you to see

**Comment by nomwerp** [comment]
@Pho3niX90  yeah i see your (now closed?) pull request #116 , is the main trick to add an empty text view below each result_view item?
```xml    <TextView android:layout_span="2" android:layout_height="1px"
        android:layout_width="fill_parent" android:text=""></TextView> ```

**Comment by nomwerp** [comment]
the layout_span doesn't seem to help for me but if you give it a background colour it nicely highlights the issue: 
device-2015-07-19-221008

**Comment by amouly** [comment]
@nomwerp you can active the "view layout bounds" on your device's Developer Tools, for debugging how the rows are rendering exactly.

**Comment by Pho3niX90** [comment]
Sorry I redid it. There are 2 file changes.

**Comment by Pho3niX90** [comment]
screenshot_2015-07-19-22-33-19 1

**Comment by Pho3niX90** [comment]
Only diff is I have the altitude in the gps as well.

**Comment by nomwerp** [comment]
thanks! will have a closer look at it later

**Comment by pires** [comment]
@nomwerp is this to be merged or closed?

**Comment by nomwerp** [comment]
please merge if you're happy with it, as you see from the screenshot there are still some minor issues but we can work on them later

**Comment by nomwerp** [comment]
@Pho3niX90 thanks for your suggestions, adding extra space does definitely help but doesn't seem to solve the issue with the gridview itself, I'll try to sort it later.

**Comment by pires** [comment]
Any updates on this?

**Comment by nomwerp** [comment]
hey,  just close it.  too far behind to merge it now

would still be nice to have a gridview...

On Thursday, 12 May 2016 04:51:53 CEST Paulo Pires wrote:


Any updates on this? 
—You are receiving this because you were mentioned.Reply to this email directly or view it on 
GitHub[1][2]




--------
[1] https://github.com/pires/android-obd-reader/pull/115#issuecomment-218734978
[2] https://github.com/notifications/beacon/AJpBTnXpek5jrmR6awFUE3cZ_y6gusb-ks5qAxRZgaJpZM4FbiXU.gif

**Pull request closed without merging**
