### PR TITLE
Remove/optimize overhead

### PR DESCRIPTION
**Pull request by Pho3niX90**
This will disable any PID's that aren't supported by the vehicle and that throws exceptions.

### CODE REVIEW

**Comment by nomwerp** [comment]
thanks,  would you mind reformatting with 2 space indents instead of 4 so that it is easier to see the changes

**Comment by Pho3niX90** [comment]
Done

**Comment by nomwerp** [comment]
thanks but i think something might have gone wrong since i still seems to be indented by 4 spaces (and the new commit 5ae30d0c2 only has one small change)?

**Comment by Pho3niX90** [comment]
I think it might be android studio that forces it 4 indents. Also the file was cleaned and reorganised.  Main part that was changed is at the  support check, just search for .apply () or .commit ()

**Comment by nomwerp** [comment]
you can change the indentation settings (for the project or in general) in android studio and tell it to reformat, that should do it. makes it so much easier to review and keep track of changes .   there has been some discussion before about reformatting the project to use 4 spaces but don't think we settled that :)

**Comment by Pho3niX90** [comment]
Okay I have tried everything now. Changed android studio to 2 lines, selected 2 indents straight in github as well.

**Comment by Pho3niX90** [comment]
Think 4 is the best to use. Reason being that all ide's do that, or suggest that. Even github understands code with 4 indents and even stackoverflow

**Comment by amouly** [comment]
@Pho3niX90 I'm requesting the change to 4 spaces indentation a long time ago :P.

**Comment by pires** [comment]
Yeah, I will change that no later than monday. @Pho3niX90 would you be so kind and wait until I've done it to reopen the PR?

**Comment by Pho3niX90** [comment]
@pires Yes sure I will wait

**Comment by pires** [comment]
Can you redo de PR with newest formatting?

**Comment by pires** [comment]
@Pho3niX90 can you create a new PR with latest formatting style?

**Pull request closed without merging**
