### PR TITLE
Organize some Strings and Layouts

### PR DESCRIPTION
**Pull request by amouly**

### CODE REVIEW

**Comment by amouly** [comment]
I can't understand why there is different types of indentation all over the app. I mean, on Layouts the indentation it's different from the Java code.

**Comment by pires** [comment]
@amouly the code should be 2 spaces indent. The XML stuff could and should follow the same thing. This tree is quite old and a lot of stuff came from very old versions so I'm thankful you noticed it and can fix it.

Please, reformat to 2 spaces indent.

Also, when you're done and feel comfortable with the PR, please squash your commits into a more discernible log.

**Comment by pires** [comment]
Refs #90

**Comment by amouly** [comment]
Thanks for your feedback. Anyway, just asking, why are you using 2 spaces for indent? The common thing on android it's using 4 spaces for indentation. This is on the Android Developer Guidelines too:

Use Spaces for Indentation
- We use 4 space indents for blocks. We never use tabs. When in doubt, be consistent with code around you.

https://source.android.com/source/code-style.html#use-spaces-for-indentation

**Comment by pires** [comment]
I always use 2 spaces on my Java code, regardless of the specific framework I'm using, in this case Android.

**Comment by amouly** [comment]
That's a shame :(. Well, i'm going to do my changes on my fork, but following the Android guidelines. Then you can extract just the strings. Thanks for this project!

**Comment by pires** [comment]
@amouly unless you don't feel like contributing other stuff in the future, I'm ok with what you suggested.
If otherwise, and if you want to provide a PR first that formats code according to Android guidelines, and if @nomwerp agrees, I am OK to get it merged. But you must understand we need to trust it because reviewing will be overwhelming.

**Comment by amouly** [comment]
@pires yes, it's understandable. Anyway, this thing about format can be easily done with Android Studio. You have and option there: Code -> Reformat code... That option organize the code based on the default config for Android, and make a log with the changes.

**Comment by nomwerp** [comment]
i'm happy to have this merged , i've build @amouly  's fork and looks good (in english at least ;) the diff here on github is actually smart enough to show both the real changes behind the formatting changes.

maybe a way ahead for now is the have all the xml formatted with 4 spaces and the keep the java code with 2 until we figure out what we want? I'd be happy to go the 4 spaces since it seems that would make it so much easier for people to contribute to this project (i know it shouldn't make a difference but still)

**Comment by pires** [comment]
@nomwerp if you're happy, i'm happy with reformatting the code. I'll merge this and reformat code tomorrow.

**Comment by amouly** [comment]
@pires awesome! Well, I made some reformatting on my fork, if you want you can compare it here to see the changes. I'm not creating the PR because there is a lot of lines changed (but not deleted code). I added most of the Dialog strings to the "strings.xml", we can merge that later.

I agreed with @nomwerp, having the code based on the guidelines would make easier to read, and maybe makes more people feel comfortable to contribute ;).

**Comment by pires** [comment]
You know IDEs allow you to configure indentation, right guys? Please, don't argue about ease of reading code, because I have a totally different opinion about many spaces. Two spaces is enough and the decision of going with four is just based on the fact that it seems it's Android guidelines.

I will reformat the code later in the day.

Thank you.

**Pull request merged**
