### PR TITLE
update obd-java-api

### PR DESCRIPTION
**Pull request by sytolk**
see https://github.com/pires/android-obd-reader/issues/136

### CODE REVIEW

**Comment by pires** [comment]
Thanks for the PR @sytolk but I can't merge it.

First of all, I don't want `obd-java-api` snapshot releases in the build. There's plenty snapshots that will break the build entirely.
Secondly, the _official_ build process is based on `build.gradle` and you haven't updated it there.

**Comment by sytolk** [comment]
Ok I`m waiting for 1.0-RC9-RELEASE :)
Do you have success with official gradle build ?
```
dependencies {
    compile 'com.github.pires:obd-java-api:1.0-RC8'
}
```

**Comment by pires** [comment]
Please, keep the PR pointed at `1.0-RC9`. I will release it as soon as https://github.com/pires/obd-java-api/pull/62 is merged.

**Comment by sytolk** [comment]
ok thanks

**Comment by pires** [comment]
@sytolk 1.0-RC9 has been released.

**Comment by sytolk** [comment]
I have changed this pull request - maven and gradle build with 1.0-RC9 version

**Pull request merged**
