### PR TITLE
Show GPS settings only if supported by the device. Cut lan/lon strings.

### PR DESCRIPTION
**Pull request by elagin**
Todo: Make a determination of support gps, orientation sensor as well as other similar devices in a separate class.

### CODE REVIEW

**Comment by pires** [comment]
@elagin is this a WIP or can I merge?

**Comment by elagin** [comment]
Merge, please.

**Comment by pires** [comment]
@elagin can you rebase please? This conflicts with #74.

**Comment by elagin** [comment]
Today I will try to do.

**Pull request merged**
