### PR TITLE
Spanish support

### PR DESCRIPTION
**Pull request by amouly**

### CODE REVIEW

**Comment by pires** [comment]
Awesome! Thank you so much @amouly

**Comment by amouly** [comment]
@pires then I found a lot of strings all over the app which are not on the Strings.xml file. You are planning to extract them on the future?

**Comment by pires** [comment]
@amouly now I do https://github.com/pires/android-obd-reader/issues/90. Do you have the time and will to take care of it? Would love to review a PR :+1:

**Comment by amouly** [comment]
@pires yes, I can take care of some of those strings. I mean, I like the app and i'm digging on how it works, so at the same time I can fix that ;).

**Comment by pires** [comment]
Awesome! You rock.

**Pull request merged**
