### PR TITLE
Enabling Upload 

### PR DESCRIPTION
**Pull request by nomwerp**
* Enable upload preferences
* Set default endpoint to example.com
* Use values from preferences in MainActivity
* Catch and log upload exceptions
* Update readme

any good reason to leave this disabled?

noticed some strange behaviour after changing the default endpoint on my device it was still set to http://www.ral.ucar.edu/~lambi/obd/get_data.php , maybe i'm missing something about the way preferences are updated?

### CODE REVIEW

**Comment by elagin** [comment]
Good idea. I would also add the ability to save the data on the sd card (if the user is allowed in the settings.)

**Comment by pires** [comment]
@nomwerp I can add support for multiple records in one PUT on `obd-server`, but this doesn't mean it's one single record in the database for all the entries, because it will be not. Unless, we were storing JSON documents.

**Comment by pires** [comment]
Thank you @nomwerp

**Comment by nomwerp** [comment]
i'm playing around with a simple php server side implementation to add the uploaded data to a database so that's where combing the data helps a lot, i haven't looked into obd-server but didn't want to break anything there.

anyway due to the asynchronous execution of the queue there is also no guarantee we get a complete set of records for every upload but should be in most cases since only called when queue is empty, maybe it should be switched around so that we first upload before filling queue again...

**Comment by pires** [comment]
So you'll be storing JSON on your database?

**Comment by nomwerp** [comment]
for now i was using json_decode and a RecursiveIteratorIterator to explode it into individual fields and insert those into my database as a set

**Comment by nomwerp** [comment]
```SQL
INSERT INTO `mytable` SET  `vin`='XXX', `SPEED`='0km/h', `ENGINE_RPM`='0 RPM', `INTAKE_MANIFOLD_PRESSURE`='0kPa', `ENGINE_LOAD`='0.0%', `longitude`=0, `latitude`=0
```

**Comment by pires** [comment]
This works if the fields don't exist beforehand on your schema?

**Comment by nomwerp** [comment]
no, at the moment just always adding all supplied fields to table before inserting , definitely not the most elegant  or secure way

**Comment by pires** [comment]
Ah OK :-) I'm trying to avoid that because we never know when a user adds a tailored command.

**Comment by nomwerp** [comment]
@elagin if we are going in the direction of storing data locally (#74) , shouldn't we rethink data upload? I'm thinking a synchronization between databases could be more appropriate

**Comment by pires** [comment]
+1 for @nomwerp idea. Please open a new issue and discuss there.

**Pull request merged**
