### PR TITLE
Update arrays.xml

### PR DESCRIPTION
**Pull request by Pho3niX90**
Added more dtc codes

### CODE REVIEW

**Comment by pires** [comment]
What is the impact of this change?

**Comment by Pho3niX90** [comment]
@pires I am busy testing the performance.

**Comment by pires** [comment]
@Pho3niX90 thank you.

**Comment by Pho3niX90** [comment]
@pires fixed some typos. Tested the performance and it's beyond perfect, no delays at all.
However, I did pick up a separate error unrelated to this though. It seem that if there are more than 9 errors it starts acting  out. Might be due to the increased frames beyond 9

**Comment by pires** [comment]
OK I will squash these commits into one and close the PR. Thank you @Pho3niX90

**Pull request closed without merging**
