### PR TITLE
update build scripts to be able to use new theme

### PR DESCRIPTION
**Pull request by nomwerp**
you'll need this, otherwise will complain about some missing dimension resources

### CODE REVIEW

**Comment by nomwerp** [comment]
TODO: update README.md too

**Comment by nomwerp** [comment]
@pires : happy to go to targetSdkVersion 21 ?

**Comment by pires** [comment]
Sure.

**Comment by pires** [comment]
@nomwerp damn, I should have asked for README.md changes but I guess I'll be doing it tomorrow. Can you take some screenshots of the app running on a moving car?

**Pull request merged**
