### PR TITLE
Fix Proguard to restore Roboguice integration.

### LINKED ISSUE #99: Proguard breaks Roboguice integration

### PR DESCRIPTION
**Pull request by pires**
Fixes #99

### CODE REVIEW

**Comment by pires** [comment]
@amouly care to try it and let me know?

**Comment by pires** [comment]
@amouly care to try it and let me know?

**Comment by amouly** [comment]
@pires yes, now it's working. Just FYI, on the build.gradle file, we have "proguard-rules.pro", but the file is named "proguard-android.txt" on the local path. You have to rename it. The system-default file it's "proguard-android.txt" (called with getDefaultProguardFile)  and that's ok.

**Comment by pires** [comment]
Fixed @amouly? Been a couple years since I last used Proguard on Android.

**Comment by amouly** [comment]
Yes, it works fine for me. And yes, the Proguard system changed a little on Studio. Thanks.

**Comment by pires** [comment]
Thank you for reporting and helping with the fix.

**Pull request merged**
