### PR TITLE
For maven users. Add maven project file

### PR DESCRIPTION
**Pull request by sytolk**
I have use https://github.com/simpligility/maven-android-sdk-deployer to import android and support library into local maven repo.
Feels free to change version of android-obd-reader. I don`t know it.
Its have problem in maven build:

/bin/sh -c cd /home/stanimir/AndroidProjects/android-obd-reader && /home/stanimir/android-sdk-linux/build-tools/22.0.1/aapt package -m -J /home/stanimir/AndroidProjects/android-obd-reader/target/generated-sources/r -f --no-crunch -M /home/stanimir/AndroidProjects/android-obd-reader/target/AndroidManifest.xml -S /home/stanimir/AndroidProjects/android-obd-reader/src/main/res -S /home/stanimir/AndroidProjects/android-obd-reader/target/unpacked-libs/cas_appcompat-v7_22.2.1/res -S /home/stanimir/AndroidProjects/android-obd-reader/target/unpacked-libs/cas_support-v4_22.2.1/res --auto-add-overlay -A /home/stanimir/AndroidProjects/android-obd-reader/target/generated-sources/combined-assets -I /home/stanimir/android-sdk-linux/platforms/android-17/android.jar --output-text-symbols /home/stanimir/AndroidProjects/android-obd-reader/target

invalid resource directory name: /home/stanimir/AndroidProjects/android-obd-reader/src/main/res btcar.svg

After remove btcar.svg from res folder Maven project build success. For what is btcar.svg file?
Can I exclude it?

### CODE REVIEW

**Comment by sytolk** [comment]
Folders in the res are only allowed to be those defined by Android. See 
http://developer.android.com/guide/topics/resources/available-resources.html
If you choose anything else you get the error "invalid resource directory name" when building your project.

**Comment by pires** [comment]
@sytolk not sure what to do with this since I can't maintain two build tools.

**Comment by sytolk** [comment]
I have see that obd-java-api project have pom.xml file. So many projects have two build systems gradle and maven for Android. You can add pom.xml file to the project and use only gradle to build it. Maven pom.xml file can be updated from maven users like me :) I know that gradle is googles choose for Android build system but simple I not like it..

**Comment by pires** [comment]
I will accept this for now. Thank you.

**Pull request merged**
