### PR TITLE
Clear dtc, show descriptions

### PR DESCRIPTION
**Pull request by Pho3niX90**
Show description for trouble codes.
Fix crash when DTC gets pulled but no codes present
Added ability to clear codes

### CODE REVIEW

**Comment by Pho3niX90** [comment]
Dependent on ResetTroubleCodes.java

**Comment by nomwerp** [comment]
it would be really great to have descriptions for the dtc codes but i'm wondering where the data come from, was it released under a license that allows us to use it? or is it public information like a standard published somewhere?

**Comment by Pho3niX90** [comment]
Not to worry. It is published all over the web. There are hundreds of websites that have the descriptions for trouble codes.

**Comment by Pho3niX90** [comment]
http://engine-codes.com/

**Comment by nomwerp** [comment]
doesn't seem to be too kind, http://engine-codes.com/about/terms.php : "Be advised that all information contained on this site is the copyrighted property of Engine-Codes.com and/or its affiliated companies. This site, Engine-Codes.com, including all other URL's owned by Engine-Codes.com and its owner, contains copyrighted material, trademarks and other proprietary information, including, but not limited to, graphics, music, photos, software, text and video. The whole contents used on or incorporated into this Web site, and the arrangement or integration of all such content and graphics are subject to any copyrights held by or licensed to Engine-Codes.com or in respect of which Engine-Codes.com is protected or entitled to by operation of any law, and all rights thereto are specifically reserved."   

The underlying problem is that car manufactures claim this as their propitiatory information

**Comment by Pho3niX90** [comment]
But as far as I know the trouble codes are all based of the OBD2 standard. 
http://www.obd-codes.com/trouble_codes/
http://www.dmv.de.gov/services/Vehicle_Services/dtc_list.pdf
http://www.outilsobdfacile.com/data-trouble-code-obd2.php

**Comment by nomwerp** [comment]
cool that dmv link looks like a good source

**Comment by Pho3niX90** [comment]
Here is the pull request for the java part: https://github.com/pires/obd-java-api/pull/51


Here are screenshots, emulated data:
screenshot_2015-07-20-22-07-09 1
screenshot_2015-07-20-22-07-13 1
screenshot_2015-07-20-22-07-28 1

**Comment by Pho3niX90** [comment]
I added altitude as well. It is useful for calculating altitude HP loss, which I will add later.

**Comment by pires** [comment]
Merged and updated to 1.0-RC5 version of dependency.

**Pull request merged**
